### ISSUE TITLE
accessControlAllowOrigin setting ignored

### ISSUE THREAD

**Issue by adankert70** [eclipse-basyx/basyx-java-components#310]
Not sure this is the correct place. For the Eclipse Basyx server the accessControlAllowOrigin setting in context.properties is ignored.
The same setting work on registry.
When setting:
accessControlAllowOrigin=*
I can see the correct response header on registry:
access-control-allow-origin: *

But for the server the accessControlAllowOrigin has no effect.
I am running from Docker container 1.3.1

**Comment by jh-isw** [comment]
Hello @FrankSchnicke, I'm using the configuration via environment variables. It does not work. I have the exact same problem like @adankert70. Any new insights on this issue?

**Comment by FrankSchnicke** [comment]
Hi @jh-isw, can you provide your startup configuration (e.g., docker compose file)?

**Comment by jh-isw** [comment]
Hi @FrankSchnicke, yes:

```
services:

  registry:
    image: eclipsebasyx/aas-registry:1.4.0
    ports:
        - 8082:4000
    environment:
        - basyxregistry_registry_backend=InMemory
        - basyxcontext_contextpath=/registry
        - basyxcontext_contextport=4000
        - basyxcontext_accesscontrolalloworigin=*
    container_name: cm-basyx-registry
    extra_hosts:
      - "host.docker.internal:host-gateway"

  aas:
    image: eclipsebasyx/aas-server:1.4.0
    container_name: cm-basyx-aasserver
    ports:
        - 4001:4001
    volumes:
      - ./aasServer:/usr/share/config
    environment:
        - basyxaas_registry_path=http://registry:4000/registry/
        - basyxaas_aas_backend=InMemory
        - basyxcontext_contextpath=/aasServer
        - basyxcontext_contextport=4001
        - basyxaas_aas_source=usr/share/config/MyPackage.aasx
        - waiting_for=[{"host":"registry","port":"4000"}]
        - basyxcontext_accesscontrolalloworigin=*
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gui: 
    image: eclipsebasyx/aas-gui:230403
    container_name: cm-basyx-aasGui 
    ports:
        - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

Looking forward to your feedback. Thanks
